version: '3.8'
name: store
services:
  db-store:
    container_name: store-db-store
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=store
      - POSTGRES_DB=store
    volumes:
      - $VOLUME/postgres/store/data:/var/lib/postgresql/data
    restart: always
    networks:
      - private-network

  adminer:
    container_name: store-adminer
    image: adminer:latest
    ports:
      - 8089:8080
    networks:
      - private-network

  discovery:
    build:
      context: ../discovery/
      dockerfile: Dockerfile
    container_name: store-discovery
    image: store-discovery:latest
    ports:
      - 8761:8761
    restart: always
    networks:
      - private-network

  gateway:
    build:
      context: ../gateway/
      dockerfile: Dockerfile
    container_name: store-gateway
    image: store-gateway:latest
    ports:
      - 8080:8080
    environment:
      - eureka.client.service-url.defaultZone=http://store-discovery:8761/eureka/
    networks:
      - private-network
    depends_on:
      - discovery

  account:
    build:
      context: ../account-resource/
      dockerfile: Dockerfile
    image: store-account:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://store-db-store:5432/store
      - spring.datasource.username=store
      - spring.datasource.password=store
      - eureka.client.service-url.defaultZone=http://store-discovery:8761/eureka/
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private-network
    depends_on:
      - db-store
      - discovery

  aluno:
    build:
      context: ../aluno-resource/
      dockerfile: Dockerfile
    image: store-aluno:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://store-db-store:5432/store
      - spring.datasource.username=store
      - spring.datasource.password=store
      - eureka.client.service-url.defaultZone=http://store-discovery:8761/eureka/
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - private-network
    depends_on:
      - db-store
      - discovery
      - account

  auth:
    build:
      context: ../auth-resource/
      dockerfile: Dockerfile
    image: store-auth:latest
    environment:
      - eureka.client.service-url.defaultZone=http://store-discovery:8761/eureka/
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - private-network
    depends_on:
      - discovery
      - account

networks:
  private-network:
    driver: bridge