version: '3.8'
name: store
services:
  db-store:
    container_name: store-db-store
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=store
      - POSTGRES_DB=store
    volumes:
      - $VOLUME/postgres/store/data:/var/lib/postgresql/data
    restart: always
    networks:
      - private-network

  adminer:
    container_name: store-adminer
    image: adminer:latest
    ports:
      - 8089:8080
    networks:
      - private-network

  aluno:
    build:
      context: ../aluno-resource/
      dockerfile: Dockerfile
    image: store-aluno:latest
    ports:
      - 8081:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://store-db-store:5432/store
      - spring.datasource.username=store
      - spring.datasource.password=store
      - eureka.client.service-url.defaultZone=http://store-discovery:8761/eureka/
    networks:
      - private-network

  instituicao:
    build:
      context: ../instituicao-resource/
      dockerfile: Dockerfile
    image: store-instituicao:latest
    ports:
      - 8082:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://store-db-store:5432/store
      - spring.datasource.username=store
      - spring.datasource.password=store
      - eureka.client.service-url.defaultZone=http://store-discovery:8761/eureka/
    networks:
      - private-network

networks:
  private-network:
    driver: bridge